services:
  - type: web
    name: crop-disease-prediction-app
    env: python
    plan: free
    region: oregon
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
